# Docs for Azure Functions action: https://github.com/Azure/functions-action

name: Build and deploy Python project to Azure Function App - createvm

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'deploy_dir' # Where deployment package will be extracted
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare Python dependencies for Azure Functions
        run: |
          mkdir -p .python_packages/lib/python${{ env.PYTHON_VERSION }}/site-packages
          cp -r venv/lib/python${{ env.PYTHON_VERSION }}/site-packages/* .python_packages/lib/python${{ env.PYTHON_VERSION }}/site-packages/

      - name: Create deployment zip package
        run: |
          mkdir staging
          shopt -s extglob
          cp -r !(staging|venv|.git|release.zip) staging/
          cp -r .python_packages staging/

      - name: Show contents of zip (debug)
        run: |
          unzip -l release.zip
          echo "Zip file size: $(du -h release.zip | cut -f1)"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          mkdir -p ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          unzip python-app/release.zip -d ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'createvm' # Replace with your Function App name
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0E89E86104924CEDBBC83ED8B62BB8B9 }}
          scm-do-build-during-deployment: false
          enable-oryx-build: false
