name: Build and deploy Python project to Azure Function App - createvm

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'deploy_dir'  # Where zip will be unzipped
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and activate virtual environment
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare Python dependencies for Azure Functions
        shell: bash
        run: |
          mkdir -p .python_packages/lib/python${{ env.PYTHON_VERSION }}/site-packages
          cp -r venv/lib/python${{ env.PYTHON_VERSION }}/site-packages/* .python_packages/lib/python${{ env.PYTHON_VERSION }}/site-packages/

      - name: Package app into release.zip
        shell: bash
        run: |
          mkdir staging
          shopt -s extglob
          cp -r !(venv|.git|staging|release.zip) staging/
          cp -r .python_packages staging/
          cd staging
          zip -r ../release.zip .

      - name: Show contents of release.zip
        run: |
          unzip -l release.zip
          echo "Zip file size: $(du -h release.zip | cut -f1)"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Unzip artifact into deployment directory
        run: |
          mkdir -p ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          unzip release.zip -d ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'createvm'  # Replace with your Function App name
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0E89E86104924CEDBBC83ED8B62BB8B9 }}
